[workspace]
dependencies_update = true # update dependencies with `cargo update`
pr_branch_prefix = "release-plz-" # PR branch prefix
pr_name = "chore(release): {{ package }} v{{ version }}"
pr_labels = ["release"] # add the `release` label to the release Pull Request
publish = false
#release_commits = "^feat:" # prepare release only if at least one commit matches a regex
changelog_config = "./cliff.toml"
repo_url = "https://github.com/BrickUIApp/BrickUIWeb"
changelog_path = "CHANGELOG.md"

git_release_type = "auto"
git_release_enable = true