# For more details on how to configure Wrangler, refer to:
# https://developers.cloudflare.com/workers/wrangler/configuration/

name = "brickui"
compatibility_date = "2025-11-25"
main = "./build/index.js"
preview_urls = false

#[build]
#command = "cargo install -q worker-build && worker-build --config ./wrangler.toml"
#cwd = "."
#watch_dir = "."

[assets]
directory = "./dist/client"
not_found_handling = "single-page-application"
binding = "ASSETS"
run_worker_first = [ "/api/*" ]

[observability]
enabled = true

[placement]
mode = "smart"

# Environment Variables
# https://developers.cloudflare.com/workers/configuration/#environment-variables
[vars]
GOOGLE_REDIRECT_URI = "https://brickui.giulioo.workers.dev/api/auth/register/google/callback"
SUPABASE_URL = "https://gbsgahfgkgjlhtvgwtur.supabase.co"

GITHUB_OWNER = "BrickUIApp"
GITHUB_REPO = "BrickUIApp"

WORKER_ENV = "production"

[env.dev.vars]
WORKER_ENV = "dev"

GOOGLE_REDIRECT_URI = "https://brickui.giulioo.workers.dev/api/auth/register/google/callback"
SUPABASE_URL = "https://gbsgahfgkgjlhtvgwtur.supabase.co"

GITHUB_OWNER = "BrickUIApp"
GITHUB_REPO = "BrickUIApp"

[env.production.vars]
WORKER_ENV = "production"

GOOGLE_REDIRECT_URI = "https://brickui.giulioo.workers.dev/api/auth/register/google/callback"
SUPABASE_URL = "https://gbsgahfgkgjlhtvgwtur.supabase.co"

GITHUB_OWNER = "BrickUIApp"
GITHUB_REPO = "BrickUIApp"

#[env.production.limits]
#cpu_ms = 1000

[[env.production.ratelimits]]
name = "API_RL"
namespace_id = "0"
simple = { limit = 10, period = 10 }

# Note: Use secrets to store sensitive data.
# https://developers.cloudflare.com/workers/configuration/secrets/

# Service Bindings (communicate between multiple Workers)
# https://developers.cloudflare.com/workers/wrangler/configuration/#service-bindings
# [[services]]
# binding = "MY_SERVICE"
# service = "my-service"
