name: CD (Deploy Cloudflare worker)

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  deploy:
    if: github.repository_owner == 'BrickUIApp'
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          persist-credentials: false
          ref: ${{ github.event.release.tag_name || github.ref_name }}

      - name: Build & Deploy Worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          wranglerVersion: "4.56.0"
