name: Sync
on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
      - run: |
          git fetch origin
          git checkout dev
          git reset --hard origin/main
          git push origin dev --force
